inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'bin/**/*'

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*  # https://github.com/rubocop/rubocop/issues/4222#issuecomment-290722962

Style/Documentation:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false
